package org.example.testCases;

import org.example.listeners.ExtentListener;
import org.example.pageObjects.AccountRegistrationPage;
import org.example.testBase.BaseTest;
import org.example.utils.DataProviderUtils;
import org.testng.Assert;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;



public class TC004_RegistrationValidationTest extends BaseTest {


    @Test
    public void verifyFirstNameRequiredValidation(){
        logger.info("Starting test:Verify firstNameRequiredValidation");
        AccountRegistrationPage accountRegistrationPage=new AccountRegistrationPage(driver);
        logger.info("Clicking Loginpage Continue button");
        accountRegistrationPage.click_login_continue_btn();
        logger.info("Entering last name using random string generator");
        accountRegistrationPage.enter_last_name(randomString());
        logger.info("Entering email using random string generator");
        accountRegistrationPage.enter_email(randomAlphanumeric()+"@gmail.com");
        logger.info("Entering phone using random string generator");
        accountRegistrationPage.enter_telephone(randomNumber());
        logger.info("Saving password generated by random string generator");
        String saved_pwd=randomAlphanumeric();
        logger.info("entering password and re-entering same password for confirmation");
        accountRegistrationPage.enter_password(saved_pwd);
        accountRegistrationPage.re_enter_password(saved_pwd);
        logger.info("clicking on no subscribe button");
        accountRegistrationPage.click_subscribe_no_btn();
        logger.info("clicking on privacy policy");
        accountRegistrationPage.click_privacy_checkbox();
        logger.info("clicking on continue button after filling form details except first name");
        accountRegistrationPage.click_registration_continue_btn();
        logger.info("checking if the first name field shows warning alert");
        Assert.assertTrue(accountRegistrationPage.fname_alert_check(),"First name required warning message did not appear when it was left empty");
    }

    @Test(dataProvider = "emailFormatData", dataProviderClass = DataProviderUtils.class)
    public void validateEmailFieldRequirement(String email) {
        AccountRegistrationPage accountRegistrationPage = new AccountRegistrationPage(driver);
        logger.info("Filling form details");
        accountRegistrationPage.click_login_continue_btn();
        accountRegistrationPage.enter_first_name(randomString());
        accountRegistrationPage.enter_last_name(randomString());
        accountRegistrationPage.enter_email(email);
        accountRegistrationPage.enter_telephone(randomNumber());
        String saved_pwd = randomAlphanumeric();
        accountRegistrationPage.enter_password(saved_pwd);
        accountRegistrationPage.re_enter_password(saved_pwd);
        accountRegistrationPage.click_subscribe_no_btn();
        accountRegistrationPage.click_privacy_checkbox();
        accountRegistrationPage.click_registration_continue_btn();

        boolean wellFormed = email.matches("^[\\w.+-]+@[\\w-]+\\.[a-zA-Z]{2,}$");

        if (wellFormed) {
            // format accepted = registration succeeded OR site says the email already exists
            boolean registered = accountRegistrationPage.confirm_heading_display_check();
            boolean alreadyRegistered = !registered && accountRegistrationPage.email_registered_alert_check();
            logger.info("Registered: " + registered + ", Already registered warning: " + alreadyRegistered);
            Assert.assertTrue(registered || alreadyRegistered,
                    "Well-formed email was not accepted by the site: " + email);
        } else {
            // malformed = browser tooltip OR the site's own DOM alert
            String browserMsg = accountRegistrationPage.email_validation_message();
            boolean browserAlertShown = browserMsg != null && !browserMsg.isEmpty();
            boolean domAlertShown = !browserAlertShown && accountRegistrationPage.email_alert_check();
            logger.info("Browser validation: '" + browserMsg + "', DOM alert: " + domAlertShown);
            Assert.assertTrue(browserAlertShown || domAlertShown,
                    "Expected a validation error for malformed email: '" + email + "' but none appeared");
        }




    }





}
